import { useEffect, useRef, useState } from 'react';
import type { CallController, CallState } from '../lib/CallController';
import type { CallParticipant } from '../../../shared/protocol';
import { Avatar } from './Avatar';
import { Icon } from './Icon';

const PHASE_LABELS = { idle: 'Chamada encerrada', media: 'Entrando na chamada…', waiting: 'Aguardando participantes', connecting: 'Conectando chamada…', connected: 'Chamada conectada', reconnecting: 'Restabelecendo conexões…' };
function useSpeaking(stream: MediaStream | null, enabled: boolean) {
  const [speaking, setSpeaking] = useState(false);
  useEffect(() => {
    if (!stream || !enabled || !stream.getAudioTracks().length) return;
    let context: AudioContext; try { context = new AudioContext(); } catch { return; }
    const source = context.createMediaStreamSource(stream); const analyser = context.createAnalyser(); analyser.fftSize = 256; source.connect(analyser);
    const samples = new Uint8Array(analyser.frequencyBinCount); let frame = 0; let last = false;
    const watch = () => { analyser.getByteFrequencyData(samples); const average = samples.reduce((total, value) => total + value, 0) / samples.length; const next = average > 16; if (next !== last) { last = next; setSpeaking(next); } frame = requestAnimationFrame(watch); };
    watch(); return () => { cancelAnimationFrame(frame); source.disconnect(); void context.close(); };
  }, [stream, enabled]); return Boolean(stream && enabled && stream.getAudioTracks().length && speaking);
}
function VideoTile({ stream, participant, local, pinned, onPin, speakerId }: { stream: MediaStream | null; participant: CallParticipant; local?: boolean; pinned: boolean; onPin: () => void; speakerId?: string }) {
  const video = useRef<HTMLVideoElement>(null); const [playBlocked, setPlayBlocked] = useState(false); const speaking = useSpeaking(stream, participant.microphone);
  useEffect(() => { const element = video.current; if (!element) return; element.srcObject = stream; if (stream) void element.play().catch(() => setPlayBlocked(true)); return () => { element.pause(); element.srcObject = null; }; }, [stream]);
  useEffect(() => { const element = video.current as (HTMLVideoElement & { setSinkId?: (id: string) => Promise<void> }) | null; if (element?.setSinkId && speakerId) void element.setSinkId(speakerId).catch(() => undefined); }, [speakerId]);
  const hidden = !participant.camera && !participant.screen;
  return <article className={`video-tile ${participant.screen ? 'is-sharing' : ''} ${speaking ? 'is-speaking' : ''} ${pinned ? 'is-pinned' : ''}`} onDoubleClick={onPin}>
    <video ref={video} autoPlay playsInline muted={local} className={hidden || !stream ? 'video-hidden' : ''} />
    {(hidden || !stream) && <div className="video-placeholder"><Avatar name={participant.displayName} url={participant.avatarUrl} /><span>{stream ? 'Câmera desativada' : 'Aguardando vídeo'}</span></div>}
    {participant.handRaisedAt && <span className="raised-hand" title="Mão levantada"><Icon name="hand" size={18} /></span>}
    <button className="pin-button" onClick={onPin} aria-label={pinned ? 'Desafixar participante' : 'Fixar participante'} data-tooltip={pinned ? 'Desafixar' : 'Fixar'}><Icon name="pin" size={16} /></button>
    <div className="video-caption"><strong>{participant.displayName}{local ? ' (você)' : ''}</strong><span>{participant.screen ? 'Compartilhando tela' : !participant.microphone ? 'Microfone desativado' : speaking ? 'Falando' : ''}</span></div>
    {playBlocked && stream && <button className="play-button" onClick={() => void video.current?.play().then(() => setPlayBlocked(false))}>Reproduzir áudio e vídeo</button>}
  </article>;
}
export function VideoCall({ state, controller, username, selfId, selfUserId, selfAvatarUrl, ownerId, speakerId }: { state: CallState; controller: CallController; username: string; selfId?: string; selfUserId: string; selfAvatarUrl: string | null; ownerId: string; speakerId?: string }) {
  const [maximized, setMaximized] = useState(false); const [panel, setPanel] = useState(false); const [pinned, setPinned] = useState<string | null>(null); const [, tick] = useState(0);
  useEffect(() => { const timer = setInterval(() => tick(value => value + 1), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => { const key = (event: KeyboardEvent) => { const target = event.target as HTMLElement; if (target.matches('input, textarea, select, [contenteditable="true"]') || event.ctrlKey || event.metaKey || event.altKey) return; const pressed = event.key.toLowerCase(); if (pressed === 'm') void controller.toggleMicrophone(); if (pressed === 'v') void controller.toggleCamera(); if (pressed === 'h') controller.toggleHand(); if (pressed === 'c') { setMaximized(false); requestAnimationFrame(() => document.querySelector<HTMLTextAreaElement>('textarea[aria-label^="Mensagem para "]')?.focus()); } if (event.shiftKey && pressed === 'f') { event.preventDefault(); setMaximized(value => !value); } if (event.key === 'Escape') setMaximized(false); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [controller]);
  const self = state.participants.find(person => person.socketId === selfId) ?? { socketId: selfId ?? 'self', userId: selfUserId, username, displayName: username, avatarUrl: selfAvatarUrl, status: 'online', inCall: true, microphone: state.microphone, camera: state.camera, screen: state.screen, attemptId: '', handRaisedAt: null } satisfies CallParticipant;
  const remotes = state.participants.filter(person => person.socketId !== selfId); const all = [self, ...remotes]; const ready = Boolean(state.localStream && state.phase !== 'media');
  const effectivePinned = pinned && all.some(person => person.socketId === pinned) ? pinned : null;
  const visible = effectivePinned ? [...all].sort((a, b) => Number(b.socketId === effectivePinned) - Number(a.socketId === effectivePinned)) : all;
  const panelPeople = [...all].sort((a, b) => a.handRaisedAt && b.handRaisedAt ? a.handRaisedAt.localeCompare(b.handRaisedAt) : a.handRaisedAt ? -1 : b.handRaisedAt ? 1 : a.displayName.localeCompare(b.displayName));
  return <section className={`call-panel ${maximized ? 'is-maximized' : ''}`} aria-label="Chamada de vídeo">
    <div className="call-panel-title"><span className="call-light" /><span>{PHASE_LABELS[state.phase]}</span><span className="meeting-timer">{duration(state.startedAt)}</span><span className={`quality quality-${state.quality}`}>{state.ecoMode && <Icon name="leaf" size={14} />}{state.ecoMode ? 'Eco · vídeo reduzido' : `Qualidade ${state.quality === 'high' ? 'alta' : state.quality === 'medium' ? 'média' : 'baixa'}`}</span><span className="call-capacity">{Math.max(1, state.participants.length)}/15</span></div>
    <div className="call-layout"><div className="video-grid" data-count={visible.length}>{visible.map(person => <VideoTile key={person.socketId} participant={person} local={person.socketId === selfId} stream={person.socketId === selfId ? state.localStream : state.remoteStreams[person.socketId] ?? null} pinned={effectivePinned === person.socketId} speakerId={speakerId} onPin={() => setPinned(value => value === person.socketId ? null : person.socketId)} />)}{remotes.length === 0 && !effectivePinned && <div className="waiting-tile"><Icon name="users" size={30} /><strong>A sala está aberta.</strong><p>Até 14 pessoas podem entrar nesta chamada.</p></div>}</div>
      {panel && <aside className="participants-panel"><header><strong>Participantes</strong><button aria-label="Fechar participantes" onClick={() => setPanel(false)}><Icon name="close" size={16} /></button></header>{panelPeople.map(person => <button key={person.socketId} onClick={() => setPinned(value => value === person.socketId ? null : person.socketId)}><Avatar name={person.displayName} url={person.avatarUrl} small /><span>{person.displayName}{person.socketId === selfId ? ' (você)' : ''}{person.userId === ownerId ? ' · proprietário' : ''}<small>{person.handRaisedAt ? <><Icon name="hand" size={13} /> Mão levantada</> : <><Icon name="mic" size={13} off={!person.microphone} /> {person.microphone ? 'ativo' : 'mutado'} · <Icon name="video" size={13} off={!person.camera} /> {person.camera ? 'ligada' : 'desligada'}</>}</small></span></button>)}</aside>}
    </div>
    <div className="reaction-cloud">{state.reactions.map(reaction => <span key={reaction.id} title={`${reaction.displayName} reagiu com ${reaction.emoji}`}><b>{reaction.emoji}</b><small>{reaction.displayName}</small></span>)}</div>
    <div className="call-controls"><button aria-label={state.microphone ? 'Silenciar microfone' : 'Ativar microfone'} disabled={!ready || state.microphoneBusy} className={!state.microphone ? 'control-off' : ''} onClick={() => void controller.toggleMicrophone()}><Icon name="mic" off={!state.microphone} /><span>{state.microphoneBusy ? 'Ativando…' : state.microphone ? 'Microfone' : 'Mutado'}</span></button><button aria-label={state.camera ? 'Desligar câmera' : 'Ligar câmera'} disabled={!ready || state.cameraBusy} className={!state.camera ? 'control-off' : ''} onClick={() => void controller.toggleCamera()}><Icon name="video" off={!state.camera} /><span>{state.cameraBusy ? 'Ativando…' : state.camera ? 'Câmera' : 'Sem câmera'}</span></button><button aria-label={state.screen ? 'Parar compartilhamento' : 'Compartilhar tela'} disabled={!ready || state.sharingBusy} className={state.screen ? 'control-active' : ''} onClick={() => void controller.toggleScreen()}><Icon name="screen" /><span>{state.screen ? 'Parar tela' : 'Compartilhar'}</span></button><button aria-label={self.handRaisedAt ? 'Abaixar a mão' : 'Levantar a mão'} className={self.handRaisedAt ? 'control-active' : ''} onClick={controller.toggleHand}><Icon name="hand" /><span>Mão</span></button>
      <span className="reaction-picker">{['👍', '👏', '❤️', '😂', '🎉', '🤔'].map(emoji => <button aria-label={`Reagir com ${emoji}`} key={emoji} onClick={() => controller.sendReaction(emoji)}>{emoji}</button>)}</span><button aria-label={state.ecoMode ? 'Desativar Modo Eco' : 'Ativar Modo Eco'} className={state.ecoMode ? 'control-active' : ''} onClick={() => void controller.setEcoMode(!state.ecoMode)}><Icon name="leaf" /><span>Eco</span></button><button aria-label="Abrir participantes" onClick={() => setPanel(value => !value)}><Icon name="users" /><span>Pessoas</span></button><button aria-label={maximized ? 'Restaurar chamada' : 'Maximizar chamada'} onClick={() => setMaximized(value => !value)}><Icon name={maximized ? 'minimize' : 'maximize'} /><span>{maximized ? 'Restaurar' : 'Maximizar'}</span></button><button aria-label="Encerrar chamada" className="control-danger" onClick={() => controller.leave()}><Icon name="call" /><span>Encerrar</span></button>
    </div><p className="shortcut-hint">Atalhos: M microfone · V câmera · H mão · C chat · Shift+F maximizar · Esc restaurar</p>
  </section>;
}
function duration(startedAt: string | null) { if (!startedAt) return '00:00'; const seconds = Math.max(0, Math.floor((Date.now() - new Date(startedAt).getTime()) / 1000)); const hours = Math.floor(seconds / 3600); return [hours, Math.floor(seconds % 3600 / 60), seconds % 60].filter((_, index) => hours || index).map(value => String(value).padStart(2, '0')).join(':'); }
